### ISSUE TITLE
About project loom 

### ISSUE THREAD

**Issue by HelloTo4x** [russdreamer/Project-Loom-Examples#1]
Hi, i am reading your project, but why do you use Project Loom ? Why don't you choose Akka ? Can you tell me the advantage and the disadvantage of Project Loom ?

**Comment by russdreamer** [comment]
@HelloTo4x  Hi, I don’t use it so far as it’s not released yet. You are able to use it with —enable-preview flag only. But almost everyone will  be using it as it will be a JDK standard soon instead of platform threads which used in reactive frameworks. Project Reactor, Java RX and I suppose Akka will change their frameworks to be based on virtual threads. Reactor already promised it. It’s not like Akka vs Project Loom. It is how Java threads will be reimplemented. Advantage - you are able to create billions of threads in traditional code style without that stack trace and callback hell. All the operation that were blocking became non-blocking for virtual threads. They are very fast (10 times faster) to start and you don’t need to use threadpool. Thread pool was using under the hood in reactive frameworks. 
Actually this my repo was just an example for a conference deficated Java multithreading and project loom.

**Comment by HelloTo4x** [comment]
thank you, can you help me compare difference Akka Actor and Project loom, and about Project loom with Reactive Programming

**Comment by russdreamer** [comment]
@HelloTo4x you can take a look at my presentation. There are disadvantages and advantages: https://docs.google.com/presentation/d/1sg3ncgIEnbVr_N-k0UzIYzQ0SzeIXWmh5B9g4ulsWSo

the main reason why reactive frameworks won’t be kill - because of a huge functionality especially backpressure mechanism. But they definitely will switch their mechanism from thread pools onto fibers.

**Comment by HelloTo4x** [comment]
thank u so much, but with Project loom, we switch thread pools -> fiber, right. so each thread(i mean OS thread) can create a lot of virtual thread in project loom, but does it use synchronize for avoid racing condition ?

**Comment by russdreamer** [comment]
@HelloTo4x virtual threads are created by jvm, not by OS. You’ll have same number of kernel threads as many CPU cores your machine has. And virtual threads are switched by JVM and finer thread itself (there are examples in my presentation). So, no OS thread scheduler is needed to switch threads for CPU cores as it was with platform ones. 

About race condition: this problem should be solved the same way as it was with platform threads. There are some upgrades related to ThreadLocal class, but it’s not really a case. 
Btw, project loom - just a team who implemented virtual threads also known as fibers in JDK. It’s not a framework 🙂

**Comment by russdreamer** [comment]
Shortly, you may have billions of virtual threads that will be served by 8 OS threads, that will be operated by 8 or less CPU cores

**Comment by HelloTo4x** [comment]
thank you so much
